// Core schema definitions
export type TableSchema = {
  key: string;
  name: string;
  fields: Array<{
    key: string;
    type: "string" | "number" | "date" | "boolean" | "id" | "enum";
  }>;
};

export type DashboardInput = {
  id?: string;
  name: string;
  description?: string;
  tables: TableSchema[];
};

export type InsightWidget = {
  id: string;
  title: string;
  description?: string;
  chartType: "line" | "bar" | "pie" | "table";
  sourceTable: string;
  metric: { op: "sum" | "count" | "avg"; field: string | null };
  groupBy?: { field: string; timeBucket?: "day" | "week" | "month" };
  filter?: Array<{ field: string; op: "=" | "in"; value: any | any[] }>;
  limit?: number;
  editable?: boolean;
  autoGenerated: boolean;
  hidden?: boolean;
};

export type GeneratedDashboard = {
  id: string;
  name: string;
  description?: string;
  detailedInsights: InsightWidget[];
};

// Semantic tagging
export type SemanticTag = "date" | "amount" | "status" | "category" | "name";
export type SemanticField = TableSchema["fields"][number] & { semanticTags: SemanticTag[] };
export type FactTable = TableSchema & { semanticFields: SemanticField[] };

const SEMANTIC_KEYWORDS: Record<SemanticTag, string[]> = {
  date: ["date", "time", "created_at", "updated_at", "order_date", "admission", "visit", "timestamp"],
  amount: ["amount", "total", "revenue", "price", "charge", "payment", "cost", "sale", "sales", "value"],
  status: ["status", "state", "stage", "phase"],
  category: ["category", "type", "segment", "group", "department", "specialty", "class"],
  name: ["name", "title", "product", "service", "item", "patient", "customer", "client", "case"],
};

const newId = () => {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") return crypto.randomUUID();
  return Math.random().toString(36).slice(2);
};

const normalizeFieldType = (raw: string | undefined): TableSchema["fields"][number]["type"] => {
  const value = (raw || "").toLowerCase();
  if (value.includes("date") || value.includes("time")) return "date";
  if (value.includes("bool")) return "boolean";
  if (value === "enum") return "enum";
  if (value.includes("int") || value.includes("num") || value.includes("decimal") || value.includes("float")) return "number";
  if (value === "id") return "id";
  return "string";
};

const tagField = (field: TableSchema["fields"][number]): SemanticField => {
  const lower = field.key.toLowerCase();
  const semanticTags = (Object.keys(SEMANTIC_KEYWORDS) as SemanticTag[]).filter((tag) =>
    SEMANTIC_KEYWORDS[tag].some((kw) => lower.includes(kw)),
  );
  return { ...field, semanticTags };
};

const toFactTables = (tables: TableSchema[]): FactTable[] => {
  const tagged = tables.map<FactTable>((table) => ({
    ...table,
    semanticFields: table.fields.map(tagField),
  }));

  const isFactTable = (table: FactTable) => {
    const hasDate = table.semanticFields.some((f) => f.semanticTags.includes("date") || f.type === "date");
    const hasAmount = table.semanticFields.some((f) => f.semanticTags.includes("amount"));
    const hasNumeric = table.semanticFields.some((f) => f.type === "number");
    return hasDate && (hasAmount || hasNumeric);
  };

  const facts = tagged.filter(isFactTable);
  if (facts.length) return facts;

  // Fallback: tables with date or amount
  return tagged.filter((table) =>
    table.semanticFields.some((f) => f.semanticTags.includes("date") || f.semanticTags.includes("amount")),
  );
};

// Template helpers
const pickDateField = (table: FactTable) =>
  table.semanticFields.find((f) => f.semanticTags.includes("date") || f.type === "date");
const pickAmountField = (table: FactTable) =>
  table.semanticFields.find((f) => f.semanticTags.includes("amount")) ||
  table.semanticFields.find((f) => f.type === "number");
const pickStatusField = (table: FactTable) => table.semanticFields.find((f) => f.semanticTags.includes("status"));
const pickCategoryField = (table: FactTable) => table.semanticFields.find((f) => f.semanticTags.includes("category"));
const pickNameField = (table: FactTable) => table.semanticFields.find((f) => f.semanticTags.includes("name"));

const looksLikeOrders = (table: FactTable) =>
  ["order", "sale", "contract", "invoice", "payment"].some((kw) => table.key.toLowerCase().includes(kw));

// Templates
export const timeSeriesTemplate = (table: FactTable): InsightWidget | null => {
  const dateField = pickDateField(table);
  const amountField = pickAmountField(table);
  if (!dateField || !amountField) return null;
  const revenueHints = ["revenue", "sales", "amount", "total", "price"];
  const isRevenue = revenueHints.some((kw) => amountField.key.toLowerCase().includes(kw));
  return {
    id: `detailed-${table.key}-revenue-over-time`,
    title: isRevenue ? "Revenue over time" : "Value over time",
    chartType: "line",
    sourceTable: table.key,
    metric: { op: "sum", field: amountField.key },
    groupBy: { field: dateField.key, timeBucket: "day" },
    editable: false,
    autoGenerated: true,
    hidden: false,
  };
};

export const statusBreakdownTemplate = (table: FactTable): InsightWidget | null => {
  const statusField = pickStatusField(table);
  if (!statusField) return null;
  return {
    id: `detailed-${table.key}-status`,
    title: looksLikeOrders(table) ? "Orders by status" : "Records by status",
    chartType: "bar",
    sourceTable: table.key,
    metric: { op: "count", field: null },
    groupBy: { field: statusField.key },
    editable: false,
    autoGenerated: true,
    hidden: false,
  };
};

export const categoryBreakdownTemplate = (table: FactTable): InsightWidget | null => {
  const categoryField = pickCategoryField(table);
  const amountField = pickAmountField(table);
  if (!categoryField || !amountField) return null;
  const title = looksLikeOrders(table) ? "Sales by category" : "Metric by category";
  return {
    id: `detailed-${table.key}-category`,
    title,
    chartType: "bar",
    sourceTable: table.key,
    metric: { op: "sum", field: amountField.key },
    groupBy: { field: categoryField.key },
    editable: false,
    autoGenerated: true,
    hidden: false,
  };
};

export const topNTemplate = (table: FactTable): InsightWidget | null => {
  const nameField = pickNameField(table);
  const amountField = pickAmountField(table);
  if (!nameField || !amountField) return null;
  const productHints = ["product", "service", "item", "sku"];
  const isProduct = productHints.some((kw) => nameField.key.toLowerCase().includes(kw));
  return {
    id: `detailed-${table.key}-top-items`,
    title: isProduct ? "Top products by revenue" : "Top items by value",
    chartType: "bar",
    sourceTable: table.key,
    metric: { op: "sum", field: amountField.key },
    groupBy: { field: nameField.key },
    limit: 5,
    editable: false,
    autoGenerated: true,
    hidden: false,
  };
};

// Generator
export function generateDetailedInsights(input: DashboardInput): InsightWidget[] {
  const factTables = toFactTables(input.tables);
  const widgets: InsightWidget[] = [];

  factTables.forEach((table) => {
    const candidates = [
      timeSeriesTemplate(table),
      statusBreakdownTemplate(table),
      categoryBreakdownTemplate(table),
      topNTemplate(table),
    ].filter(Boolean) as InsightWidget[];
    widgets.push(...candidates);
  });

  // Dedupe by title and by core signature (table + metric + groupBy)
  const seenTitle = new Set<string>();
  const seenSignature = new Set<string>();
  const deduped: InsightWidget[] = [];

  widgets.forEach((widget) => {
    const signature = `${widget.sourceTable}::${widget.metric.field ?? "count"}::${widget.groupBy?.field || ""}`;
    if (seenTitle.has(widget.title) || seenSignature.has(signature)) return;
    seenTitle.add(widget.title);
    seenSignature.add(signature);
    deduped.push(widget);
  });

  // Cap between 3 and 8 widgets
  const MIN = 3;
  const MAX = 8;
  const limited = deduped.slice(0, MAX);
  if (limited.length >= MIN) return limited;

  // If too few, pad with generic placeholders from available tables
  const remaining = Math.min(MIN - limited.length, factTables.length);
  for (let i = 0; i < remaining; i += 1) {
    const table = factTables[i];
    limited.push({
      id: `detailed-${table.key}-fallback-${i + 1}`,
      title: `Metric overview (${table.name})`,
      chartType: "bar",
      sourceTable: table.key,
      metric: { op: "count", field: null },
      editable: false,
      autoGenerated: true,
      hidden: false,
    });
  }

  return limited;
}

export function generateDashboard(input: DashboardInput): GeneratedDashboard {
  const detailedInsights = generateDetailedInsights(input);
  return {
    id: input.id ?? newId(),
    name: input.name,
    description: input.description,
    detailedInsights,
  };
}
